/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practica004;

import practica004.GUI.GenericErrorDialog;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reiso
 */
public class FiltradoRegistrosv2 extends javax.swing.JDialog {

    /**
     * Creates new form FiltradoRegistrosv2
     */
    public FiltradoRegistrosv2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Registros");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Edad", "Sexo", "Estado Civil"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Buscar por Matricula");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 550);

        setBounds(0, 0, 867, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
    // Obtén la matrícula desde el jTextField1
    String matriculaBuscada = jTextField1.getText();
    
    if (matriculaBuscada == null || matriculaBuscada.isEmpty()) {
        // El campo de matrícula está vacío
        GenericErrorDialog GER = new GenericErrorDialog(null, true);
        GER.setErrorMessage("El campo de matrícula no puede estar vacío. Proporcione los datos correctos.");
        GER.setVisible(true);
    } else if (matriculaBuscada.matches("\\d{6}")) {
        // La matrícula es válida, llama a la función para cargar los datos
        cargarDatosDesdeArchivoTabla("archivo.txt", jTable1, matriculaBuscada);
    } else {
        // La matrícula no cumple con el formato esperado
        GenericErrorDialog GER = new GenericErrorDialog(null, true);
        
        if (!matriculaBuscada.matches("\\d+")) {
            // La matrícula no es un número entero
            GER.setErrorMessage("La matrícula no puede ser una cadena de texto. Debe proporcionar 6 dígitos enteros positivos.");
        } else if (matriculaBuscada.length() != 6) {
            // La matrícula no tiene 6 dígitos
            GER.setErrorMessage("La matrícula es un dato que contiene 6 dígitos enteros, no puede contener más ni menos.");
        }
        
        GER.setVisible(true);
    }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltradoRegistrosv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltradoRegistrosv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltradoRegistrosv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltradoRegistrosv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FiltradoRegistrosv2 dialog = new FiltradoRegistrosv2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void cargarDatosDesdeArchivoTabla(String archivo, JTable table, String matriculaBuscada) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String matricula = null;
            String nombre = null;
            String edad = null;
            String sexo = null;
            String estadoCivil = null;

            String linea;
            while ((linea = br.readLine()) != null) {
                if (linea.startsWith("Matrícula:")) {
                    matricula = linea.substring("Matrícula:".length()).trim();
                } else if (linea.startsWith("Nombre:")) {
                    nombre = linea.substring("Nombre:".length()).trim();
                } else if (linea.startsWith("Edad:")) {
                    edad = linea.substring("Edad:".length()).trim();
                } else if (linea.startsWith("Sexo:")) {
                    sexo = linea.substring("Sexo:".length()).trim();
                } else if (linea.startsWith("Estado Civil:")) {
                    estadoCivil = linea.substring("Estado Civil:".length()).trim();
                }

                // Si se han obtenido todos los valores y la matrícula coincide con la buscada, agregar fila al modelo de la tabla
                if (matricula != null && nombre != null && edad != null && sexo != null && estadoCivil != null) {
                    if (matricula.equals(matriculaBuscada)) {
                        model.addRow(new Object[]{matricula, nombre, edad, sexo, estadoCivil});
                    }
                    // Reiniciar los valores para la próxima fila
                    matricula = null;
                    nombre = null;
                    edad = null;
                    sexo = null;
                    estadoCivil = null;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
