package CalculadoraMain;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reiso
 */
public class CalculadoraPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraPrincipal
     */
    public CalculadoraPrincipal() {
        initComponents();
        gsa = new Calculadora();
        mc = new MetodosOperaciones();
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciona una opcion"));
        jPanel2.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Sumar");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(10, 20, 120, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Restar");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(10, 50, 80, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Multiplicar");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton3MousePressed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(10, 80, 110, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Dividir");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton4MousePressed(evt);
            }
        });
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(10, 110, 110, 21);

        jButton5.setText("Limpiar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 150, 72, 23);

        jButton6.setText("Salir");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(100, 150, 72, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(350, 20, 180, 180);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sumar"));
        jPanel3.setLayout(null);

        jLabel1.setText("Entero 1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 30, 50, 16);

        jLabel2.setText("Entero 2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 100, 50, 16);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(80, 30, 80, 22);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(80, 100, 80, 22);

        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(40, 240, 72, 23);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(60, 200, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 250, 180, 280);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Restar"));
        jPanel4.setLayout(null);

        jLabel4.setText("Entero 3");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 30, 50, 16);

        jLabel5.setText("Flotante 1");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 100, 60, 16);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(91, 30, 80, 22);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(91, 100, 80, 22);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(70, 200, 0, 0);

        jButton2.setText("Aceptar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(50, 240, 72, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(230, 250, 180, 280);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Multiplicar"));
        jPanel5.setLayout(null);

        jLabel7.setText("Flotante 2");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 30, 60, 16);

        jLabel8.setText("Entero 4");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 90, 60, 16);
        jPanel5.add(jTextField5);
        jTextField5.setBounds(100, 30, 80, 22);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField6);
        jTextField6.setBounds(100, 90, 80, 22);
        jPanel5.add(jLabel9);
        jLabel9.setBounds(80, 200, 0, 0);

        jButton3.setText("Aceptar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(60, 240, 72, 23);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(480, 250, 190, 280);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dividir"));
        jPanel6.setLayout(null);

        jLabel10.setText("Flotante 3");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 30, 60, 16);

        jLabel11.setText("Flotante 4");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 90, 60, 16);
        jPanel6.add(jTextField7);
        jTextField7.setBounds(90, 30, 80, 22);
        jPanel6.add(jTextField8);
        jTextField8.setBounds(90, 90, 80, 22);
        jPanel6.add(jLabel12);
        jLabel12.setBounds(70, 200, 0, 0);

        jButton4.setText("Aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(60, 240, 72, 23);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(690, 250, 180, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 560);

        setBounds(0, 0, 926, 578);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        // TODO add your handling code here:
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jRadioButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MousePressed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton3MousePressed

    private void jRadioButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MousePressed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jRadioButton4MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        int entero1 = 0, entero2 = 0;
        gsa.setEntero1(Integer.parseInt(jTextField1.getText()));
        gsa.setEntero2(Integer.parseInt(jTextField2.getText()));
        gsa.realizarSuma(entero1, entero2);
        jLabel3.setText("" + gsa.getResultadoSuma());
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        int entero3 = 0;
        float flotante1 = 0.0f;
        gsa.setEntero3(Integer.parseInt(jTextField3.getText()));
        gsa.setFlotante1(Float.parseFloat(jTextField4.getText()));
        gsa.realizarResta(entero3, flotante1);
        jLabel6.setText("" + gsa.getResultadoResta());
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        float flotante2 = 0.0f;
        int entero4 = 0;
        gsa.setFlotante2(Float.parseFloat(jTextField5.getText()));
        gsa.setEntero4(Integer.parseInt(jTextField6.getText()));
        gsa.realizarMultiplicacion((int) flotante2,entero4);
        jLabel9.setText("" + gsa.getResultadoMultiplicacion());
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        float flotante3 = 0.0f, flotante4 = 0.0f;
        gsa.setFlotante3(Float.parseFloat(jTextField7.getText()));
        gsa.setFlotante4(Float.parseFloat(jTextField8.getText()));
        gsa.realizarDivision(flotante3, flotante4);
        jLabel12.setText("" + gsa.getResultadoDivision());
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        jLabel3.setText(null);
        jLabel6.setText(null);
        jLabel9.setText(null);
        jLabel12.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
    private Calculadora gsa;
    private MetodosOperaciones mc;
}
